### ISSUE TITLE
[BUG]: get_index_roulette_wheel_selection(self, list_fitness: np.array)

### ISSUE THREAD

**Issue by Cai-Chengyi** [thieu1995/mealpy#100]
### Description of the bug

在运行**optimizer.py**文件下的get_index_roulette_wheel_selection(self, list_fitness: np.array)函数时，如果list_fitness.ptp() == 0，则x=np.random.choice(range(0, size), p=1.0/size)会报错，原因是TypeError: object of type 'float' has no len()，在删去p=1.0/size后便能正常运行。
其中，np.random.choice函数对p的描述如下
p: 1-D array-like, optionalThe probabilities associated with each entry in a. If not given, the sample assumes a uniform distribution over all entries in a.

### Steps To Reproduce

None

### Additional Information

None

**Comment by Cai-Chengyi** [comment]
好吧，是return np.random.choice(range(0, size), p=1.0/size)会报错，x=np.random.choice(range(0, size), p=1.0/size)是我debug的时候写的

**Comment by thieu1995** [comment]
@Cai-Chengyi,

Yep, I'm aware of this bug. Please download the alpha version of the next version using.

`pip install mealpy==2.5.3a1`

In this alpha version, I also add more options to MultiTask class. 
Thanks for reporting it anyway.
