### ISSUE TITLE
[FEAT]: About multi-objective BFO algorithem

### ISSUE THREAD

**Issue by weishibin-ucas** [thieu1995/mealpy#102]
### Description

Hi there, I really like this project, but I couldn't find the implementation part of the multi-objective bacterial foraging algorithm. The source code seems to generate a single target by weighting and averaging multiple targets using np.dot function. Do you have a plan to implement a multi-objective bacterial foraging algorithm similar to NSGAII？Thanks.

**Comment by thieu1995** [comment]
Hi @weishibin-ucas ,

Currently, we don't have plan to implement MOO (multi-objective optimization) for all algorithms like NSGA-II. Whenever we turn a single objective optimization to MOO, we need to change the designation and operators of original algorithm. That is not the purpose of this library. 
If you want to work with MOO, we suggest you can try https://pymoo.org/ and design your own operators for those algorithm you want.
