### ISSUE TITLE
[FEAT]: Add irregular constraints

### ISSUE THREAD

**Issue by zhubing96** [thieu1995/mealpy#103]
### Description

How do I add an irregular constraint in mealpy, such as x1+x2>0. The code with the rule constraints is as follows.

### Additional Information

import numpy as np
from mealpy.bio_based.BBO import BaseBBO
def fitness_function(solution):
    return np.sum(solution ** 2)
problem_dict1 = {"fit_func": fitness_function, "lb": [-10, -15, -4, -2, -8], "ub": [10, 15, 12, 8, 20], "minmax": "min"}
epoch = 1000
pop_size = 50
p_m = 0.01
elites = 2
model = BaseBBO(epoch, pop_size, p_m, elites)
best_position, best_fitness = model.solve(problem_dict1)
print(f"Solution: {best_position}, Fitness: {best_fitness}")

**Comment by thieu1995** [comment]
@zhubing96 ,
Sorry for late reply, you can use our custom Problem class like this:

```
import numpy as np
from mealpy.bio_based.BBO import BaseBBO
from mealpy.utils.problem import Problem


# Our custom problem class
class MyProblem(Problem):
    def __init__(self, lb=None, ub=None, minmax="min", **kwargs):
        super().__init__(lb, ub, minmax, **kwargs)

    def g1(self, x):
        return x[0] + x[1] > 0
    
    def penalty_func(self, val):
        if val > 1:
            return val**2
        elif 0 < val <= 1:
            return val 
        else:
            return 0

    def fit_func(self, x):
        return np.sum(x ** 2) + self.penalty_func(self.g1(x))


prob = MyProblem(lb=[-10, -15, -4, -2, -8],
                 ub=[10, 15, 12, 8, 20],
                 minmax="min")
epoch = 1000
pop_size = 50
p_m = 0.01
elites = 2
model = BaseBBO(epoch, pop_size, p_m, elites)
best_position, best_fitness = model.solve(prob)
print(f"Solution: {best_position}, Fitness: {best_fitness}")
```

You can use my penalty_func() or you can design your own penalty function.

**Comment by thieu1995** [comment]
Here is the results with above code. 

![image](https://github.com/thieu1995/mealpy/assets/12763861/88a3bdbf-6bc4-456e-af00-391bfc184d91)
