### ISSUE TITLE
[BUG]:  OriginalGWO not work as expected 

### ISSUE THREAD

**Issue by mtabbasi** [thieu1995/mealpy#104]
### Description of the bug

When I compare the results of [OriginalGWO](https://github.com/thieu1995/mealpy/blob/5540b378bc96729ddc55d4826e4ff94201e339ec/mealpy/swarm_based/GWO.py#L11) in mealpy to [GWO](https://github.com/7ossam81/EvoloPy/blob/master/optimizers/GWO.py) in evolopy library, I get a worse result. I think there is a misbehavior in [OriginalGWO](https://github.com/thieu1995/mealpy/blob/5540b378bc96729ddc55d4826e4ff94201e339ec/mealpy/swarm_based/GWO.py#L11).

### Steps To Reproduce

Solve a complex optimization problem with the gwo algorithm implemented in the evolopy library and compare the results with the OriginalGWO algorithm

**Comment by thieu1995** [comment]
Hi @mtabbasi,

Thanks for pointing out this bug. I replaced the inner for loop of GWO by vectorization. But forgot about the coefficients. 
I have fixed in the new alpha version.

`$ pip install mealpy==2.5.4a4`

You can try the new version and see the difference.

**Comment by mtabbasi** [comment]
Hi @thieu1995,
It's working in the alpha version. 
Thanks
