### ISSUE TITLE
[FEAT]: MEALPY for feature selection?

### ISSUE THREAD

**Issue by omina91** [thieu1995/mealpy#107]
### Description

How to use Mealpy for feature selection problem?
I would like to use some optimizers to choose the best features for my regression problem? How to do it with Mealpy?

**Comment by thieu1995** [comment]
@omina91 ,

Thanks for using Mealpy in your problem. You can check out this library. It shows how to use Mealpy for feature selection (supported both regression and classification problems)
https://github.com/thieu1995/mafese

**Comment by omina91** [comment]
@thieu1995 thank you so much. I love your library bro. It contains so many optimizers that I can use. Appreciate your effort for making this library.
