### ISSUE TITLE
Improved Teaching Learning based Opitmization ( I-TLBO)

### ISSUE THREAD

**Issue by moshaad7** [thieu1995/mealpy#11]
[rao2012 improved TLBO.pdf](https://github.com/thieu1995/mealpy/files/6258409/rao2012.improved.TLBO.pdf)

**Comment by thieu1995** [comment]
Hi @moshaad7 ,
You can check the most recent commits to get your requested algorithm. Thanks
I will close this issues soon.

**Comment by moshaad7** [comment]
Thank you so much, thieu
