### ISSUE TITLE
[BUG]: OriginalZOA Phase2 S1：Parameter R is the constant number equal to 0.01 in referenced paper.

### ISSUE THREAD

**Issue by UGBeyond** [thieu1995/mealpy#110]
### Description of the bug

![image](https://github.com/thieu1995/mealpy/assets/112760513/43219a15-3b6b-4290-953b-bf1f8e18cf94)

mealpy==2.5.4
While learning the algorithm I realized that the constant settings here do not match the constants in the reference paper, I am not sure which constant to use for the next step, looking forward to a definitive answer, thanks to the contributors for their work!

### Steps To Reproduce

![image](https://github.com/thieu1995/mealpy/assets/112760513/aacf8aaa-5f59-4a4e-845a-1f93f7213595)

![image](https://github.com/thieu1995/mealpy/assets/112760513/47851836-b381-4bfc-9268-822461d46678)

**Comment by thieu1995** [comment]
@UGBeyond,

It should be 0.01 like in the paper. You can change it directly in Pycharm. However, please considering my note for this algorithm in the Table of ReadMe file. Of course, if you don't fear your research will be affected when the paper of this algorithm is retracted, then we have nothing to say here. Feel free to use and develop as you want.

**Comment by UGBeyond** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thieu1995/mealpy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月3日(星期天) 凌晨0:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thieu1995/mealpy] [BUG]: OriginalZOA Phase2 S1：Parameter R is the constant number equal to 0.01 in referenced paper. (Issue #110)

Thank you for your reply and reminder in your busy schedule. I wish you all the best.
