### ISSUE TITLE
TypeError: fitness_function() missing 1 required positional argument: 'data'

### ISSUE THREAD

**Issue by Med-Rokaimi** [thieu1995/mealpy#111]
Thank you for this great work.
I'm applying this example in mha-hyper-parameter-mlp-time-series.py, I got this error

TypeError                                 Traceback (most recent call last)
[<ipython-input-14-4c3ca1161632>](https://localhost:8080/#) in <cell line: 75>()
    103     # model = FPA.OriginalFPA(epoch=5, pop_size=20)
    104     model = GWO.OriginalGWO(epoch=5, pop_size=20)
--> 105     model.solve(problem)
    106 
    107     print(f"Best solution: {model.solution[0]}")

3 frames
[/usr/local/lib/python3.10/dist-packages/mealpy/utils/problem.py](https://localhost:8080/#) in __set_functions(self, kwargs)
    120             else:
    121                 tested_solution = self.amend_position(tested_solution, self.lb, self.ub)
--> 122         result = self.fit_func(tested_solution)
    123         if type(result) in self.SUPPORTED_ARRAY:
    124             result = np.array(result).flatten()

TypeError: fitness_function() missing 1 required positional argument: 'data'

I have tries to change the mealpy version from 1.5.4 and 1,5.2 but still not working. could you please help?

**Comment by thieu1995** [comment]
Hi @Med-Rokaimi ,

Could you show me your fitness function?  Or better, show me your whole code?

**Comment by Med-Rokaimi** [comment]
This is my code. But, It worked fine after I removed the second paramater from the fitness function, to be like this : 
def fitness_function(solution):
      .......
and I defined data variable as a global variable.


This is the whole code with witch I got the error

from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import Dense
from keras import optimizers
import statsmodels.datasets.co2 as co2
from permetrics.regression import RegressionMetric


def decode_solution(solution, data):
    # batch_size = 2**int(solution[0])
    # # 1 -> 1.99 ==> 1
    # # 2 -> 2.99 ==> 2
    # # 3 -> 3.99 ==> 3
    #
    # epoch = 10 * int(solution[1])
    # # 10 * 70 = 700
    # # 10 * 200 = 2000
    #
    # opt_integer = int(solution[2])
    # opt = OPT_ENCODER.inverse_transform([opt_integer])[0]
    # # 0 - 0.99 ==> 0 index ==> should be SGD (for example)
    # # 1 - 1.99 ==> 1 index ==> should be RMSProp
    #
    # learning_rate = solution[3]
    #
    # network_weight_initial_integer = int(solution[4])
    # network_weight_initial = WOI_ENCODER.inverse_transform([network_weight_initial_integer])[0]
    #
    # act_integer = int(solution[5])
    # activation = ACT_ENCODER.inverse_transform([act_integer])[0]
    #
    # n_hidden_units = int(solution[6])

    batch_size = 2 ** int(solution[0])
    epoch = 10 * int(solution[1])
    opt_integer = int(solution[2])
    opt = data["OPT_ENCODER"].inverse_transform([opt_integer])[0]
    learning_rate = solution[3]
    network_weight_initial_integer = int(solution[4])
    network_weight_initial = data["WOI_ENCODER"].inverse_transform([network_weight_initial_integer])[0]
    act_integer = int(solution[5])
    activation = data["ACT_ENCODER"].inverse_transform([act_integer])[0]
    n_hidden_units = int(solution[6])
    return {
        "batch_size": batch_size,
        "epoch": epoch,
        "opt": opt,
        "learning_rate": learning_rate,
        "network_weight_initial": network_weight_initial,
        "activation": activation,
        "n_hidden_units": n_hidden_units,
    }


def generate_data():
    
    ......
    return {"X_train": X_train, "y_train": y_train, "X_test": X_test, "y_test": y_test, "n_steps": seq_len}



def generate_loss_value(structure, data):
    # define model
    model = Sequential()
    model.add(Dense(structure["n_hidden_units"], activation=structure["activation"],
                    input_dim=data["n_steps"], kernel_initializer=structure["network_weight_initial"]))
    model.add(Dense(1))

    # Compile model
    optimizer = getattr(optimizers, structure["opt"])(learning_rate=structure["learning_rate"])
    model.compile(optimizer=optimizer, loss='mse')

    # fit model
    model.fit(data["X_train"], data["y_train"], epochs=structure["epoch"], batch_size=structure["batch_size"], verbose=2)

    # We take the loss value of validation set as a fitness value for selecting
    # the best model demonstrate prediction
    y_pred = model.predict(data["X_test"])

    evaluator = RegressionMetric(data["y_test"], y_pred, decimal=6)
    return evaluator.mean_squared_error()


from sklearn.preprocessing import LabelEncoder
from mealpy.evolutionary_based import FPA
from mealpy.swarm_based import GWO


def fitness_function(solution, data):
    structure = decode_solution(solution, data)
    fitness = generate_loss_value(structure, data)
    return fitness



# LABEL ENCODER
OPT_ENCODER = LabelEncoder()
OPT_ENCODER.fit(['SGD', 'RMSprop', 'Adagrad', 'Adadelta', 'Adam', 'Adamax', 'Nadam'])  # domain range ==> 7 values

WOI_ENCODER = LabelEncoder()
WOI_ENCODER.fit(['uniform', 'lecun_uniform', 'normal', 'zero', 'glorot_normal', 'glorot_uniform', 'he_normal', 'he_uniform'])

ACT_ENCODER = LabelEncoder()
ACT_ENCODER.fit(['softmax', 'softplus', 'softsign', 'relu', 'tanh', 'sigmoid', 'hard_sigmoid', 'linear'])

data = generate_data()  #{"X_train": X_train, "y_train": y_train, "X_test": X_test, "y_test": y_test, "n_steps": seq_len}
data["OPT_ENCODER"] = OPT_ENCODER
data["WOI_ENCODER"] = WOI_ENCODER
data["ACT_ENCODER"] = ACT_ENCODER

LB = [1, 5, 0, 0.01, 0, 0, 5]
UB = [3.99, 20.99, 6.99, 0.5, 7.99, 7.99, 50]



problem = {
    "fit_func": fitness_function,
    "lb": LB,
    "ub": UB,
    "minmax": "min",
    "log_to": None,
    "save_population": False,
    "data": data,
}
model = FPA.OriginalFPA(epoch=5, pop_size=20)
#model = GWO.OriginalGWO(epoch=5, pop_size=20)
model.solve(problem)

print(f"Best solution: {model.solution[0]}")
sol = decode_solution(model.solution[0], data)

print(f"Batch-size: {sol['batch_size']}, Epoch: {sol['epoch']}, Opt: {sol['opt']}, "
        f"Learning-rate: {sol['learning_rate']}, NWI: {sol['network_weight_initial']}, "
        f"Activation: {sol['activation']}, n-hidden: {sol['n_hidden_units']}")

**Comment by thieu1995** [comment]
Hi @Med-Rokaimi ,

Yes, the fitness function when you define it. You should pass only "solution" parameter. So that is why when you removed the 2nd parameter, it works. I know for the problem with mixed type of variables like this, It is hard for user to defines and runs algorithm. There will be a new version that handle all of this nonsense. But it will take time for me to re-design the whole library since it is too big now. 
Do you have any other question?

**Comment by Med-Rokaimi** [comment]
Thank you very much @thieu1995  for your prompt response.
If I can put this question here, my goal is to use LSTM for multivariate time series forecasting. I'm wondering if this will work fine? and I will need only to  rewrite the sequential model (the network)?
I mean if the changes will be only with these 4 lines to define LSTM:
model = Sequential()
model.add(Dense(structure["n_hidden_units"], activation=structure["activation"],
input_dim=data["n_steps"], kernel_initializer=structure["network_weight_initial"]))
model.add(Dense(1))
thank you in adavnce

**Comment by thieu1995** [comment]
@Med-Rokaimi ,

Yes, it will work fine. However, LSTM is different than MLP network. You need to preprocess the data differently. Other than that, just change the defined model with your LSTM model code.

**Comment by Med-Rokaimi** [comment]
Thank you in advance
