### ISSUE TITLE
add a python file to compare differernt algorithms 

### ISSUE THREAD

**Issue by tangling123** [thieu1995/mealpy#113]
### Description

bro, your code is wonderful, can you add a sample Python file including several algorithms to compare, and generate CSV and PNG file? I am comparing my code to the algorithms in mealpy and citing your paper, but I don't see in the paper how to compare multiple algorithms.

**Comment by thieu1995** [comment]
@tangling123 ,

Thank you for using it. Have you check MultiTask class yet?

https://github.com/thieu1995/mealpy/blob/master/examples/run_multitask.ipynb
https://github.com/thieu1995/mealpy/blob/master/examples/run_multitask.py

**Comment by tangling123** [comment]
Thank you for getting back to me. But I can run  https://github.com/thieu1995/mealpy/blob/master/examples/run_multitask.py in Windows. But it doesn't work on Mac, I will check https://github.com/urllib3/urllib3/issues/3020 again.

**Comment by tangling123** [comment]
Thank you very much, I've managed to get the code to run!

**Comment by thieu1995** [comment]
@tangling123 , 

You are welcome. I will close this issue now.
