### ISSUE TITLE
How to access the prediction values obtained from the best global solution, please?

### ISSUE THREAD

**Issue by Med-Rokaimi** [thieu1995/mealpy#116]

**Comment by Med-Rokaimi** [comment]
I used model.solution[1][0] to access the fitness value associated to the best global solution. But I couldn't figure out how to return the predicted values associated to the best global solution.

**Comment by thieu1995** [comment]
Hi @Med-Rokaimi ,

Recall to this issue. https://github.com/thieu1995/mealpy/issues/112
The predicted values are from keras model. It is not related to Mealpy optimizer. You can use the solution from mealpy to construct a new keras model based on the best hyper-parameter found (solution). Please remember this is black-box optimization. It doesn't really care what is your problem, and what is going on in the fitness function. It only care about the value return from fitness function.

**Comment by thieu1995** [comment]
@Med-Rokaimi ,

Also you should name an optimizer as an optimizer, so it will not miss match with keras neural network model.
Then you should have a code like this:

```
def create_network(structure, data):
    # define model
    model = Sequential()
    model.add(Dense(structure["n_hidden_units"], activation=structure["activation"],
                    input_dim=data["n_steps"], kernel_initializer=structure["network_weight_initial"]))
    model.add(Dense(1))

    # Compile model
    optimizer = getattr(optimizers, structure["opt"])(learning_rate=structure["learning_rate"])
    model.compile(optimizer=optimizer, loss='mse')

    # fit model
    model.fit(data["X_train"], data["y_train"], epochs=structure["epoch"], batch_size=structure["batch_size"], verbose=2)
    
    return model 
    
optimizer = FPA.OriginalFPA(epoch=5, pop_size=20)
optimizer.solve(problem)

print(f"Best solution: {optimizer.solution[0]}")
model = create_network(optimizer.solution[0], DATA)
y_pred = model.predict(DATA["X_test"])
```

**Comment by Med-Rokaimi** [comment]
Thank you. so helpful.
