### ISSUE TITLE
[FEAT]: Inquiry about Customizing Optimization Starting Point

### ISSUE THREAD

**Issue by cumttc** [thieu1995/mealpy#119]
### Description

 I am particularly interested in customizing the starting point for optimization, and I was wondering if you could provide some guidance on how to achieve this.

Best regards,

**Comment by thieupu** [comment]
Hi @cumttc,

You can pass a matrix of positions with shape (pop_size, n_dims) in a solver like this:
https://mealpy.readthedocs.io/en/latest/pages/general/advance_guide.html#starting-solutions

**Comment by cumttc** [comment]
Hi@thieupu


> Hi @cumttc,
> 
> You can pass a matrix of positions with shape (pop_size, n_dims) in a solver like this: https://mealpy.readthedocs.io/en/latest/pages/general/advance_guide.html#starting-solutions

If my initial solution is [1, 2, 3, 4], then the 'starting_solutions' I need to pass in is np.ones((pop_size, 4)) @ np.diag(1, 2, 3, 4). 
Is it correct?

**Comment by thieupu** [comment]
@cumttc ,

Mealpy is population-based algorithms, so the `starting_solutions` of any algorithm is a matrix of population and problem size. 
If your initial solution is [1, 2, 3, 4]. And you have pop_size = 10 (agents). 
Then you should set `starting_solutions` like this:

```python
import numpy as np

pop_size = 10
problem_size = n_dims = 4

initial = np.array([1, 2, 3, 4])
starting = [ initial + np.random.uniform(-0.1, 0.1, n_dims) for _ in range(0, pop_size-1) ]
starting_solutions = np.array( [initial] + starting )
```

**Comment by cumttc** [comment]
Thanks for the answer, but one more question:
What should I do if I have additional parameters that are not involved in the optimization, but need to be passed into the objective function?

**Comment by thieu1995** [comment]
@cumttc ,

Then you should define a custom problem like this:
https://mealpy.readthedocs.io/en/latest/pages/general/advance_guide.html#custom-problem

You can pass anything you want into that class.
