### ISSUE TITLE
[BUG]: FOX Algorithm Exploration phase issue

### ISSUE THREAD

**Issue by maulberto3** [thieu1995/mealpy#122]
### Description of the bug

Hello, great repo, while myself translating some algos to Jax, I noticed that FOX algorithm Exploration phase has an issue.

### Steps To Reproduce

According to paper, it'd be:
`self.g_best.solution * self.generator.random(self.problem.n_dims) * (self.mint * aa)`
instead of (as it's currently in repo):
`self.g_best.solution + self.generator.standard_normal(self.problem.n_dims) * (self.mint * aa)`

That is, it'd sum, not multiply; and use random instead of normal. Extract of paper attached.
![image](https://github.com/thieu1995/mealpy/assets/22672781/ebe35dd3-20cc-4c72-ad16-319c9b286c80)

### Additional Information
Currently don't know if I'm attaching a different or revised version of FOX algo.

**Comment by thieu1995** [comment]
Hi @maulberto3 ,

Thanks for reporting this bug. I will fix it soon. 
However, normally, it should be `sum` not `multiply`. Of course, I can't judge this algorithm since I haven't compare both version. I will add both versions for user to test.

**Comment by maulberto3** [comment]
> Hi @maulberto3 ,
> 
> Thanks for reporting this bug. I will fix it soon. However, normally, it should be `sum` not `multiply`. Of course, I can't judge this algorithm since I haven't compare both version. I will add both versions for user to test.

Hi, I'm with you on that one, can't say if it's a typo of the paper itself, I'm now suspicious, more so when you read the paper, writing is not what you'd expect and I can't with how they treated t (t1 in this repo)... I found out about all this while doing some jax code translations.
