### ISSUE TITLE
Confused about time bound stopping condition

### ISSUE THREAD

**Issue by Xeuva** [thieu1995/mealpy#127]
The time bound stopping condition currently uses the criterion `current_time >= self.max_time` to calculate the running duration. However, `current_time` represents the runtime of the entire program, not just the solver. It seems `current_time - self.start_time  >= self.max_time` would be more precise.

**Comment by thieu1995** [comment]
@Xeuva,

Thanks for pointing out the bug. It has been fixed in latest commit.
