### ISSUE TITLE
[FEAT]: Customize the starting population

### ISSUE THREAD

**Issue by sshenbao** [thieu1995/mealpy#128]
### Description

I want to use a custom function to define the position of the initial particles, because my solution needs to meet an equation requirement, and if I use uniform selection of particles, there is a high probability that the first generation will not get a viable solution, so how do I do that?

**Comment by thieu1995** [comment]
Hi @sshenbao,

You can check out the starting_positions variable in .solve() function.
https://mealpy.readthedocs.io/en/latest/pages/general/advances/starting_positions.html?highlight=starting

**Comment by sshenbao** [comment]
![QQ截图20240102135234](https://github.com/thieu1995/mealpy/assets/155406861/c4253541-20d8-40cb-a5da-d4f65f350ea0)
Why can't the example given on the official website work?

**Comment by thieu1995** [comment]
@sshenbao ,

I forgot the update the key name in fm_problem dictionary. It should be "obj_func", not "fit_func".

**Comment by sshenbao** [comment]
Thanks for the answer, I tried to use different initial population generation methods in DEAP, and it seems that the impact on the final optimization result is not as big as I thought, I don't know if you have studied a single-objective optimization problem constrained by the equation, the impact of the feasible solution proportion of the initial population on the efficiency and results of the final iteration?

**Comment by thieu1995** [comment]
I think the intial population doesn't matter much on the final result. The matter is how you setup the penalty function and of course, the efficiency of equations in algorithm.

**Comment by sshenbao** [comment]
OK,thanks
