### ISSUE TITLE
Dynamic constraints

### ISSUE THREAD

**Issue by sshenbao** [thieu1995/mealpy#130]
If I want to add a dynamic penalty function or an adaptive penalty function, and I need to transfer parameters such as the current number of iterations or the proportion of feasible solutions in the fitness function, how do I do this, do I modify it in the source code, or should I build the relevant algorithm myself and modify it during the iteration.

**Comment by thieu1995** [comment]
Hi @sshenbao,

I have thought about it, but not found any solution. Because in this library, we separate Optimizer and Problem. Penalty function belongs to Problem class, we have to define before program runs. But current epoch is changing while the program runs.

**Comment by sshenbao** [comment]
Thanks for the answer, I'll try to rebuild the algorithm。
