### ISSUE TITLE
[BUG]: The implementation of 'HS' (OriginalHS) lead to an error when solving the Bukin's functions family

### ISSUE THREAD

**Issue by Mimismo91** [thieu1995/mealpy#131]
### Description of the bug

Thank you for the excellent development of this super usefull library.

I've been notice that the implementation of the algorithm 'HS' (OriginalHS) lead to an error when trying to solve the Bukin's function family. Bein more precise, Im using the following syntaxis to declare de functions:
{'func': lambda x: 100 * x[1]**2 + 0.01 * abs(x[0] + 10),'name': 'Bukin 4', 'optimal': 0.00000, 'bounds': [(-15, -5), (-3, 3)]}

So the the console returns this error:
Traceback (most recent call last):
"C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mealpy\music_based\HS.py", line 159, in evolve
    delta = self.dyn_fw * self.generator.normal(self.problem.lb, self.problem.ub)  # Gaussian(Normal)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "numpy\\random\\_generator.pyx", line 1220, in numpy.random._generator.Generator.normal
  File "_common.pyx", line 600, in numpy.random._common.cont
  File "_common.pyx", line 505, in numpy.random._common.cont_broadcast_2
  File "_common.pyx", line 384, in numpy.random._common.check_array_constraint
ValueError: scale < 0

This usually occurs when the scale parameter (typically the standard deviation in a normal distribution) is negative.
The error specific line is:
delta = self.dyn_fw * self.generator.normal(self.problem.lb, self.problem.ub)

A potential solution would be to correctly calculate the mean and standard deviation to use in the normal function. This could be done, for example, by using the midpoint of the range as the mean and a fraction of the range as the standard deviation. Here is an example of how you might do this:

mean = (self.problem.lb + self.problem.ub) / 2
std_dev = abs(self.problem.ub - self.problem.lb) / 6  # This assumes a range of +/- 3 standard deviations
delta = self.dyn_fw * self.generator.normal(mean, std_dev)

This way I got it to work propperly when solving this functions.

Best regards.

### Steps To Reproduce

1- Try to solve: {'func': lambda x: 100 * x[1]**2 + 0.01 * abs(x[0] + 10),'name': 'Bukin 4', 'optimal': 0.00000, 'bounds': [(-15, -5), (-3, 3)]}

**Comment by thieu1995** [comment]
Hi @Mimismo91,

Thanks for reporting the bug. Indeed, that is my mistake, at that time, I forgot that is normal function not uniform function.
I have fixed the bug based on your suggestion in latest commit.
