### ISSUE TITLE
[BUG]: Walrus optimisation algorithm missing equations of feeding step

### ISSUE THREAD

**Issue by Saksham3005** [thieu1995/mealpy#134]
### Description of the bug

First equation of feeding process is not provided.

### Steps To Reproduce

1. Go to code

**Comment by thieupu** [comment]
Hi @Saksham3005,

What do you mean by missing equation? Here is the equation from the paper.

![image](https://github.com/thieu1995/mealpy/assets/145318253/12448356-f31e-4d87-8882-27897b3341c4)

Here is the code I provided. 
https://github.com/thieu1995/mealpy/blob/master/mealpy/swarm_based/WaOA.py#L69
