### ISSUE TITLE
Mealpy + Neural Network (Optimize Neural Network Hyper-parameter) with K-Fold

### ISSUE THREAD

**Issue by safrizalardanaa** [thieu1995/mealpy#138]
### Description

Please make an example of code about Mealpy + Neural Network (Optimize Neural Network Hyper-parameter) with K-Fold for classification problem, because the code in your documentation is still error

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-82-745465ec224b> in <cell line: 3>()
      1 # Create and train the HybridMlp model
      2 model = HybridMlp(dataset, n_hidden_nodes, epoch, pop_size)
----> 3 model.training()

<ipython-input-81-8dbc4491fa29> in training(self)
     53         self.optimizer = AO.OriginalAO(self.epoch, self.pop_size)
     54         print(self.optimizer.solve(self.problem))
---> 55         self.solution, self.best_fit = self.optimizer.solve(self.problem)
     56 
     57     def fitness_function(self, solution):

TypeError: cannot unpack non-iterable Agent object

**Comment by thieupu** [comment]
Hi @safrizalardanaa ,

I have built a completely new library for this task. Please check it here: https://github.com/thieu1995/MetaPerceptron
You can use MhaMlpRegressor, MhaMlpClassifier as an estimator from Scikit-Learn. Feel free to re-open if you still need more help.
