### ISSUE TITLE
Implementation of Horse - herd optimization algorithm

### ISSUE THREAD

**Issue by shan8tanu** [thieu1995/mealpy#14]
Hello! I am an electrical engineer working on digital filters using meta-heurisitic algorithms and came across this horse - herd optimization algorithm. Unfortunately, not much has been written about it, could you maybe take a look at the original paper and try to implement it? Thanks!
[Horseherdoptimizationalgorithm.pdf](https://github.com/thieu1995/mealpy/files/6525755/Horseherdoptimizationalgorithm.pdf)

**Comment by thieu1995** [comment]
Hi @shan8tanu,

I have read the paper above, it is like a fake paper to me. 
The equations don't fit as a whole. Some symbols are not clear how to calculate it. 

You should avoid this kind of paper, don't waste your time in it. There are lots of good and recent algorithms in this library you can try.

**Comment by shan8tanu** [comment]
Oh, thank you for that. Did look a bit odd to me, some things did not make sense.

Anyways, thanks for taking a look!
