### ISSUE TITLE
[BUG]:  Base GWO's code in the documentation is incorrect

### ISSUE THREAD

**Issue by gssakash** [thieu1995/mealpy#142]
### Description of the bug

The code for initializing and using the Base GWO [Grey Wolf Optimization] Algorithm is incorrect and needs to be fixed as it gives the error - 
``ImportError: cannot import name 'BaseGWO' from 'mealpy.swarm_based.GWO' (/usr/local/lib/python3.10/dist-packages/mealpy/swarm_based/GWO.py)
``

### Steps To Reproduce

1. Go to the documentation for the [Base GWO Model](https://mealpy.readthedocs.io/en/latest/pages/models/mealpy.swarm_based.html#mealpy.swarm_based.GWO.OriginalGWO)
2. Run the code

**Comment by thieu1995** [comment]
@gssakash Some document page has been out of date. I haven't had time to update the docs website.
You can use this to check all available optimizers that are supported.

```
import mealpy
print(mealpy.get_all_optimizers())
```
