### ISSUE TITLE
In this example, we use SMA optimize to optimize the hyper-parameters of SVC model.[BUG]: 

### ISSUE THREAD

**Issue by bulewhales** [thieu1995/mealpy#146]
### Description of the bug

An error occurs here !
![image](https://github.com/thieu1995/mealpy/assets/44105223/a2f3c050-9609-494d-9d93-a00f2f6b1ce1)

### Steps To Reproduce

see picture
![image](https://github.com/thieu1995/mealpy/assets/44105223/93ce71d1-34e6-41c4-8347-f4fbdbd27514)

### Additional Information

none

**Comment by bulewhales** [comment]
Machine learning example is missing a letter 'a'

**Comment by thieu1995** [comment]
Hi @bulewhales,

Can you upload your code here? In the figure, I don't see any bug. What do you mean by missing letter "a"?

**Comment by bulewhales** [comment]
> Hi @bulewhales,
> 
> Can you upload your code here? In the figure, I don't see any bug. What do you mean by missing letter "a"?

![image](https://github.com/thieu1995/mealpy/assets/44105223/848414e5-383d-425d-8f7f-e69fbf47016c)
In your machine learning example, there is one less letter 'a'.

**Comment by thieu1995** [comment]
@bulewhales,

Thank you, I see it now. It has been fixed.
