### ISSUE TITLE
Algorithm Variants Implementation Request

### ISSUE THREAD

**Issue by gad1991** [thieu1995/mealpy#15]
Please I wonder if you may implement three well-known variants of PSO and DE, namely, respectively, [Compherehnsive Learning PSO (CLPSO)](https://ieeexplore.ieee.org/document/1637688), [Self-adaptive DE (SaDE)](https://ieeexplore.ieee.org/document/1554904), and [Improving the search performance of SHADE using linear population size reduction (L-SHADE)](https://doi.org/10.1109/CEC.2014.6900380) as three additions to your brilliant mealpy package. Attached links to relative papers.

**Comment by thieu1995** [comment]
Hi @gad1991 ,

Long time no see, you can check the most recent commits to get your requested algorithms. Thanks
