### ISSUE TITLE
[FEAT]: add start point to algorithms

### ISSUE THREAD

**Issue by zorka5** [thieu1995/mealpy#150]
### Description

Hi, I enjoy the library very much! As far as I know, right now there is no easy way of adding initial point to population. I would love to be able to add start point (for example like in scipy differential_evolution  x0 param). Thanks!

**Comment by thieu1995** [comment]
Hi @zorka5,

We do have that feature. 
https://mealpy.readthedocs.io/en/latest/pages/general/advance_guide.html#starting-solutions

**Comment by zorka5** [comment]
Thank you!! Couldn't find it :D
