### ISSUE TITLE
[BUG]: Could not get right problem name

### ISSUE THREAD

**Issue by Code-Newborn** [thieu1995/mealpy#155]
### Description of the bug

![image](https://github.com/thieu1995/mealpy/assets/47051839/6ebe60dc-898d-488d-a74f-5b479e2030ea)

### Steps To Reproduce

1. definite a custom-problem class, give it a "name" attribute, like following pic:
![image](https://github.com/thieu1995/mealpy/assets/47051839/da2e2779-b5a3-4a53-b809-ac07c7251184)

2. Get problem's name through function model.problem.get_name() or attribute  model.problem.name
![image](https://github.com/thieu1995/mealpy/assets/47051839/18dd3618-3ddd-47ac-b73f-ecd210b62b1e)

3. we cant get the right name

### Additional Information

and i try to fix it like following, and i wonder if it is fitted
![image](https://github.com/thieu1995/mealpy/assets/47051839/3afc9a15-17ef-4603-88d3-32de9fb2d571)

_No response_

**Comment by thieu1995** [comment]
@Code-Newborn,

I don't know why you can't get the right name. However, I still can do it without any error. 

![image](https://github.com/thieu1995/mealpy/assets/12763861/cbf13170-a449-48b6-9d66-4adb5aeb4266)

Above, I use this example: https://github.com/thieu1995/mealpy/blob/master/examples/applications/run_cloud_computing.py
And get the right one.

**Comment by Code-Newborn** [comment]
![image](https://github.com/thieu1995/mealpy/assets/47051839/f80f4c28-4f29-48c0-9cea-5e1c955d2659)

i think it is caused by the code: "self.name=name" and the formal parameter [name="Squared"], you can try this part to verify it

**Comment by thieu1995** [comment]
@Code-Newborn ,

Yes, you are right. We should not define the name in custom class. It is already defined in Problem class.
I will update all examples.

![image](https://github.com/thieu1995/mealpy/assets/12763861/624efd04-1b3a-47e1-af7c-74133e660381)
