### ISSUE TITLE
[FEAT]: Some variables are continuous values, while others are discrete values. How should we handle them

### ISSUE THREAD

**Issue by wanfeng132** [thieu1995/mealpy#160]
### Description

Some variables have continuous values from 0 to 1, while others can only take 0 or 1

**Comment by thieupu** [comment]
@wanfeng132 
It is very easy to design your variables in this case. Please check out this example:
https://github.com/thieu1995/mealpy/blob/master/examples/utils/run_Mix_Type.py

**Comment by abqlearner** [comment]
> @wanfeng132 It is very easy to design your variables in this case. Please check out this example: https://github.com/thieu1995/mealpy/blob/master/examples/utils/run_Mix_Type.py

When I try to run the example file, I find the following error.
`Problem: <mealpy.utils.problem.Problem object at 0x000001D8B7ABBAD0>
Bounds: [<mealpy.utils.space.FloatVar object at 0x000001D8F3CDE810>, <mealpy.utils.space.IntegerVar object at 0x000001D8954F6790>, <mealpy.utils.space.StringVar object at 0x000001D8B7ABBCD0>, <mealpy.utils.space.FloatVar object at 0x000001D8B96859D0>, <mealpy.utils.space.PermutationVar object at 0x000001D8B9A61ED0>, <mealpy.utils.space.BinaryVar object at 0x000001D8B9A61F90>, <mealpy.utils.space.BoolVar object at 0x000001D8B9A62110>]
...
KeyError: '0.1'`
