### ISSUE TITLE
C_PSO error, mealpy/swarm_based/PSO.py:304: RuntimeWarning: invalid value encountered in true_divide

### ISSUE THREAD

**Issue by Doradx** [thieu1995/mealpy#18]
```
/lib/python3.8/site-packages/mealpy/swarm_based/PSO.py:304: RuntimeWarning: invalid value encountered in true_divide
  cx_best_0 = (g_best[self.ID_POS] - self.lb) / (self.ub - self.lb)       # Eq. 7
```
The error shows that `(self.ub - self.lb)` may be zero, and `cx_best_0 ` wiil be `NaN`.

I have seen the source code that the `self.lb` and `self.ub` will be updated during the iterations, which may lead to the error. 
https://github.com/thieu1995/mealpy/blob/c558d5a4cb2699645bcce04a72f99a1d13647d3b/mealpy/swarm_based/PSO.py#L311-L314

But I'm not sure how to fix it.

**Comment by thieu1995** [comment]
Hi @Doradx , @alfred20-20 

The new version is out now. Could you guys try to use and give me some feedbacks? Thanks.

Best regards.
