### ISSUE TITLE
Self-defined constraints

### ISSUE THREAD

**Issue by seulixian** [thieu1995/mealpy#20]
It seems that I can only set upper and lower bound for the variables now. How can I use self-defined constraints when employing swarm-based algorithms like PSO?

**Comment by thieu1995** [comment]
Hi @seulixian
 
Currently, this library can't handle the self-defined constraints. I will think about that. If you have any ideas please share some.

Best regards,

**Comment by thieu1995** [comment]
Hi @seulixian ,

The new version is out now. In this new version you can defined your own constraints. However, the only way to handle the constraints is currently using Penalty method like in the example of the ReadMe file. 

I have no idea about handling constraints using other techniques. If you have some documents or suggestions, don't hesitate to let me know.

Best regards/
