### ISSUE TITLE
BaseGWO does not meet lb and ub limitations

### ISSUE THREAD

**Issue by pooyasa** [thieu1995/mealpy#21]
Hi,
First of all, thank you for this amazing package.
However I believe there is a problem in the implementation of the GWO algorithm. It does not keep the output variables in the required upper and lower bound limitation.
Here is my code and the output
Also, I did not see this problem in the WOA.

```
from mealpy.swarm_based.GWO import BaseGWO

import math 

def fitness_rastrigin(position):
  fitness_value = 0.0
  for i in range(len(position)):
    xi = position[i]
    fitness_value += (xi * xi) - (10 * math.cos(2 * math.pi * xi)) + 10
  return fitness_value

verbose = False
epoch = 10
pop_size = 50

lb1 = [1, 1, 1]
ub1 = [5, 10, 100]

md1 = BaseGWO(fitness_rastrigin, lb1, ub1, verbose, epoch, pop_size)
best_pos1, best_fit1, list_loss1 = md1.train()
print(md1.solution[0])
print(md1.solution[1])
```

output for GWO:

> [ 1.00673293  0.96909221 -0.01711316]
> 2.207618350381356

output for WOA:

> [1. 1. 1.]
> 3.0

**Comment by thieu1995** [comment]
Hi @pooyasa 

Thanks for pointing out the problem. I may forget to use the amend_solution function before calculating the fitness value. 
Currently, I'm upgrading the library, so I will fix this error shortly.

Best regards,

**Comment by thieu1995** [comment]
Hi @pooyasa ,

The new version is out now. I fixed some problems you mentioned above.
Please try and give me some feedbacks.

Best regards.
