### ISSUE TITLE
Implementing Parallel Computation of Fitness for indivuduals

### ISSUE THREAD

**Issue by mehrdadfazli** [thieu1995/mealpy#22]
Hi,
I was wondering if the parallelization of the fitness calculations is done in the package. Looking at the source codes I do not think it is implemented yet. However, I guess for most (if not all) of the population-based heuristic algorithms the task of calculating fitness for individuals is independent. Therefore, it would be fairly easy to use a pool of workers (multiprocessing module for example) to parallelize fitness calculations. This becomes especially more important for large-scale problems with a pretty heavy objective function.
Thanks for the thorough implementation of meta-heuristic algorithms.

**Comment by thieu1995** [comment]
Hi @mehrdadfazli 

Thanks for your comment.  You are right, the calculating fitness for individuals is independent and very important for large-scale problems.
I have thoughts about it but haven't done it. So I will implement it in the future.

Best regards,

**Comment by thieu1995** [comment]
Hi @mehrdadfazli ,

I have a second thought. Still, I think calculating fitness for individuals is independent in the initial phase only. Because in updating phase of the algorithm. They need to calculate the fitness to compare with the previous one. Then they will keep the better one. 
What is your thought on that?

**Comment by xRotorTwoBlade** [comment]
Hey there,
First of all, a massive compliment for this fantastic collection of easy-to-apply optimization algorithms! About parallelism: Maybe my method is relatively uncommon, but I use a cost function that needs a lot of time (for simulating wind turbines and evaluating the runs). Right now, each simulation+evaluation runs after the other, because only one vector of parameters is transferred to the cost function. If there were an option to transfer all parameters (e.g. positions) of one whole generation to the cost function, that would speed up my calculations multiple times (It's currently days). I changed it already in the PSO.py by splitting up the population loop, but maybe you got a smarter idea?
Anyhow, thanks for all your work!
Cheers, Fabian

PS: Here is the change in "train":

            x_new_as_list = []
            for i in range(self.pop_size):
                v_new = w * v_list[i] + self.c1 * uniform() * (pop_local[i][self.ID_POS] - pop[i][self.ID_POS]) +\
                            self.c2 * uniform() * (g_best[self.ID_POS] - pop[i][self.ID_POS])
                x_new = pop[i][self.ID_POS] + v_new             # Xi(new) = Xi(old) + Vi(new) * deltaT (deltaT = 1)
                x_new = self.amend_position_random_faster(x_new)

            ########################################### CHANGED BY ANSFAB ##############################################
                x_new_as_list.append(x_new)

            print('CHANGED CODE FOR MULTIPLE RUNS IN PARALLEL')
            fit_new = self.get_fitness_position(x_new_as_list)

            for i in range(self.pop_size):
                pop[i] = [x_new_as_list[i], fit_new[i]]

                # Update current position, current velocity and compare with past position, past fitness (local best)
                if fit_new[i] < pop_local[i][self.ID_FIT]:
                    pop_local[i] = [x_new_as_list[i], fit_new[i]]


            #    pop[i] = [x_new, fit_new]
            #
            #    # Update current position, current velocity and compare with past position, past fitness (local best)
            #    if fit_new < pop_local[i][self.ID_FIT]:
            #        pop_local[i] = [x_new, fit_new]

            ########################################### CHANGED BY ANSFAB ##############################################

                ## batch size idea
                if self.batch_idea:
                    if (i + 1) % self.batch_size == 0:
                        g_best = self.update_global_best_solution(pop_local, self.ID_MIN_PROB, g_best)
                else:
                    if (i + 1) % self.pop_size:
                        g_best = self.update_global_best_solution(pop_local, self.ID_MIN_PROB, g_best)
            self.loss_train.append(g_best[self.ID_FIT])
            if self.verbose:
                print(">Epoch: {}, Best fit: {}".format(epoch+1, g_best[self.ID_FIT]))

**Comment by thieu1995** [comment]
Hi @mehrdadfazli ,

Thank you so much for helping. An amazing example for paralleling the code. 
However, most of the recent algorithms, they designed in the way the next solution may depend on the previous solution. But I have an idea to parallel it already. The rest I will implement as your suggestion.

In this library, I tried to use as a minimal dependency (third party) as possible. Therefore, I tried threading, multiprocessing, concurrent (ThreadPoolExecutor and ProcessPoolExecutor), and multiprocess. 
I found that multiprocessing has a problem with windows (need the __main__ condition).
And, I also found that multiprocess is actually slowing down the ThreadPoolExecutor. 
Therefore, I decide to use a concurrent module for the new version.

Again, thanks for your detailed example. It helps me so much.
I will try to release the new version as soon as possible. Til needs to do some works for new features also converting all algorithms. 

Best regards,

**Comment by mehrdadfazli** [comment]
@thieu1995 You are welcome! You definitely know more than me and have delved into all of those algorithms to implement them. I am glad the example helped.

I also experienced the same issues with the "multiprocessing" module. You seem to have them already figured out.

Thanks for the great work and wish you the best of luck.

**Comment by thieu1995** [comment]
Hi @mehrdadfazli , @xRotorTwoBlade 

The new version is out now. You guys can try and give me some feedbacks.
Thank again for your huge suggestions.

Best regards,
