### ISSUE TITLE
Implementation of TPO (Tree Physiology Optimization) ?

### ISSUE THREAD

**Issue by xRotorTwoBlade** [thieu1995/mealpy#24]
Dear thieu1995,

I love your collection of metaheuristic algorithms. I'm currently searching for the "best" algorithms for controller tuning. Among many algorithms that you have already implemented, Tree Physiology Optimization seems to be a promising candidate. Could you implement this one as well? 

Here are the sources: https://www.degruyter.com/document/doi/10.1515/jisys-2017-0156/html 
And an application: https://link.springer.com/content/pdf/10.1007/s00521-018-3588-9.pdf

Best regards,
Fabian

**Comment by thieu1995** [comment]
Hi @xRotorTwoBlade ,

I will implement this algorithm, thanks for asking and sharing the source.

Best regards,

**Comment by xRotorTwoBlade** [comment]
Hi @thieu1995,
huge thanks for your commitment! I'm pretty excited about how well it might work.
All the best,
Fabian
