### ISSUE TITLE
Parameters are out of bounds for ArchOA, HGS 

### ISSUE THREAD

**Issue by robobachu** [thieu1995/mealpy#25]
Dear Thieu1995,

Thank you for the wonderful set of optimization algorithms. I ran the test with the Archimedes Optimization Algorithm (ArchOA), Hunger Games Search (HGS) algorithm and set the parameters as follows:
lb = [0, 0, 0]
ub = [1, 1, 1]
problem_size = 3
 
verbose = False
epoch = 500
pop_size = 50

But when the algorithm runs for a number of rounds, it fails, because one of the parameters is out of bounds.
=> How to fix this?

Best regards.

**Comment by thieu1995** [comment]
Hi @robobachu 
The new version is out. Try it and give me some feedbacks.

Best regards,
