### ISSUE TITLE
ImporError: cannot import name 'Root'

### ISSUE THREAD

**Issue by xiaoli0113** [thieu1995/mealpy#26]
Dear thieu 1995
First of all, thank you very much for your collection of the meta heuristics algorithms.
I noticed there was a sentence (from mealpy.optimizer import Root) in each basic algorithm, but I cannot find the 'Root' in optimizer, I wonder if there is something I should change.

Best regards.

**Comment by dsemeraro2** [comment]
Hi, any news on this?

Best regards.

**Comment by thieu1995** [comment]
Hi @dsemeraro2, @xiaoli0113 
I had updated the new version. Could you try it out and give me some feedbacks?

Best regards.

**Comment by hebrotem** [comment]
I am having the same issue using the mha_hydrid. the problem persist in 2.1.2 also

**Comment by thieu1995** [comment]
@hebrotem 
If your still get the error, it means that you are installing multiple version on your machine. 
Could you try to uninstall it from your machine and install the newest version.

```
pip uninstall mealpy
pip install meapy==2.1.2
```
