### ISSUE TITLE
I think a private note got pushed to live by accident

### ISSUE THREAD

**Issue by JasonNeuswanger** [thieu1995/mealpy#28]
First, thanks for putting together an awesome package of optimization algorithms. It's saved me a ton of time. However, in the next release I thought you might want to update the line that prints "Fucking for real?" before the path of each figure saved (linechart.py line 51).

**Comment by thieu1995** [comment]
@JasonNeuswanger ,

Lol, That is my print test. I forgot to delete it. Thank bro. :))

**Comment by thieu1995** [comment]
@JasonNeuswanger 

I release a new version and fix some problems. I will close this issue now. Thanks
