### ISSUE TITLE
examples代码运行问题

### ISSUE THREAD

**Issue by creatorcyh2021** [thieu1995/mealpy#33]
您好，为什么运行您的examples代码 run_test_SFO.py会出现
![image](https://user-images.githubusercontent.com/76993587/146036020-c0959a9c-e1aa-4c8b-a327-3ebb4d7b6b30.png)

**Comment by thieu1995** [comment]
Hi @creatorcyh2021 ,

Writing an example for each optimizer like the previous mealpy is wasted so much of my time. So I decided to make a few tutorial videos to guide how to use mealpy library. 
So the folder example you are running above is for the previous mealpy version, not the latest version, that is why you got that error.

Please watch the tutorial videos with link in the ReadMe.md. If you get any trouble leave it here. I will try to support you.

Best regards

**Comment by creatorcyh2021** [comment]
好的谢谢您的回复

**Comment by creatorcyh2021** [comment]
我有一点建议，希望您能给视频加上字幕，对于我这种英语不好的听起来有点费力，再次感谢您

**Comment by thieu1995** [comment]
Thank @creatorcyh2021 , I will try to add CC to the video. My speaking skill is so bad, I guess you won't understand. Maybe you can read the code and try to understand it.

**Comment by tumu1234** [comment]
您好 我也在用这个库请问您是怎么安装的呢?我有这样的错误
ModuleNotFoundError: No module named 'mealpy.bio_based'; 'mealpy' is not a package
