### ISSUE TITLE
Optimazing Neural network training

### ISSUE THREAD

**Issue by Mosi-2000** [thieu1995/mealpy#34]
Hi @thieu1995;
Actually, I'm trying to optimize a neural network with 2 hidden layer and one output. here's the list of neurons in each layer from input to output: [9, 8, 4, 1]. 
I want to use Sparrow search algorithm to optimize the weight and bias, but I don't know how can I use BaseSpaSA and asking for a list of weight and bias. I will send u my code and I appreciate if u help me to understand how I get a nested list from BaseSpaSA. 

![A1](https://user-images.githubusercontent.com/93074310/146260783-297a60fc-2daf-46d4-8dd8-7333911629b5.JPG)
![A2](https://user-images.githubusercontent.com/93074310/146260791-a7d5eb00-19b1-49c6-8de9-126b47faea40.JPG)
![A3](https://user-images.githubusercontent.com/93074310/146260821-8a78d319-01b4-4f21-861b-61159e207e4b.JPG)
![A4](https://user-images.githubusercontent.com/93074310/146260832-c39f73a1-b45d-4d1e-96dc-1d990b771f7b.JPG)

**Comment by thieu1995** [comment]
Hi @Mosi-2000 ,

You should watch the tutorial video, it will answer your question.
https://youtu.be/auq7Na1Meus
