### ISSUE TITLE
Optimizing NN by optimization algorithm

### ISSUE THREAD

**Issue by Mosi-2000** [thieu1995/mealpy#35]
Hi @thieu1995 
I'm trying to optimize a neural network with Sparrow search algorithm but I don't how can I use BaseSpaSA in order to get a nested list for a MLPClassifier. just imagine that we have a list of neurons like [9, 8, 4, 1] which means 9 neurons as input, two hidden layer and one neuron for output. I firmly need your help.
Thanks in advance.

**Comment by thieu1995** [comment]
Hey @Mosi-2000 ,

Have you watched the tutorial video? I'm not here to work for you. I've already made the video to help people. If you don't want to spend your time and watch it. Don't come here asking for help.
If you still don't understand then you need to study what is neural network, what is metaheuristic algorithm.
You can't get anything from BaseSpaSA. It is an algorithm. Not even related to your MLPClassifier.

**Comment by Mosi-2000** [comment]
Hey @thieu1995 
I appreciate for answering. I just find out that u recently add some videos and now I'm watching them.
Best regards

**Comment by thieu1995** [comment]
@Mosi-2000 ,
Alright, if you can't code for yourself, you can modifiy my code in the folder: https://github.com/thieu1995/mealpy/tree/master/examples/applications/keras
It is exactly what you are looking for by adding 1 more hidden layer in the keras code. 
I will close this issue now, if you get any trouble during the process. Create new issue.
