### ISSUE TITLE
Run Your code: mha-hyper-parameter-mlp-time-series

### ISSUE THREAD

**Issue by Uzma-GM** [thieu1995/mealpy#36]
Hi, 
![123](https://user-images.githubusercontent.com/90240838/146412594-271b0aa6-8066-4560-9cbd-481335b6b8ed.png)
Before changing your code for my problem. I just run your code. its showing an error.

**Comment by Uzma-GM** [comment]
I resolved the issue by using this: from tensorflow.keras import optimizers instead of from keras import optimizers. Thanks

**Comment by thieu1995** [comment]
Hi @Uzma-GM ,
It is depended on your environment (pip or conda) and your tensorflow/keras version. 
Good to see you found the solution. I will close this issue now.
Thanks
