### ISSUE TITLE
Pareto-like sequential sampling heuristic for global optimization

### ISSUE THREAD

**Issue by ketsonroberto** [thieu1995/mealpy#44]
My co-worker published the following paper recently

https://link.springer.com/article/10.1007/s00500-021-05853-8

It is a pareto-like sequential sampling methods. He tested on several benchmark problems. I believe it would be interesting to have this one as well...We use this method for several applications and it is rather robust in the searching process.

**Comment by thieu1995** [comment]
@ketsonroberto 
The idea of the paper is looking good tho. I will try to implement it. Thanks for suggesting the paper.

**Comment by ketsonroberto** [comment]
Great! Thanks!

**Comment by tumu1234** [comment]
May I ask how the blogger should modify the parameters for machine learning optimization? Should he modify the fitness function

**Comment by ketsonroberto** [comment]
This is an answer from the author: The efficiency of these algorithms (like any other optimization algorithm) are always dependent on how sensitive the objective function is for changes, and the nature of the objective functions, e.g., multimodal, convex, non-convex, etc. This will influence, in the PSS algorithm, the \alpha factor. If your objective function is more of a convex nature, high \alpha (let's say 0.9-0.95) would be good as it weakens the diversification process and increases the intensification process to refine the final solutions (increase accuracy). However, for nonconvex functions (depending on how hard it is) we can use \alpha of 0.7-0.9 or just 0.85. However, this process can be repeated and you will find out which one is the best. Another factor might be the population size too, the more the better. However, the latter depends on the computational complexity and the affordable computational capacity of the application. It means if the objective function is fast to evaluate, you can use more and this will generally give better solutions.

**Comment by thieu1995** [comment]
@ketsonroberto ,

I just updated your friend algorithm in the new version. You can try to use it now. Thanks.
https://github.com/thieu1995/mealpy/blob/v2.4.0/mealpy/math_based/PSS.py

**Comment by ketsonroberto** [comment]
This is great!! Many thanks!!!
