### ISSUE TITLE
Does mealpy offer the feature selection for classification/ regression problem? 

### ISSUE THREAD

**Issue by hanamthang** [thieu1995/mealpy#46]
Thank you for the collection of quality metaheuristic optimization algorithm. Can we use the mealpy for any feature selection tasks? 

Many thanks,
Thang

**Comment by thieu1995** [comment]
@hanamthang 
You can watch the full tutorials here. May give you some tips to design feature selection for classification or regression problem using mealpy.
https://www.youtube.com/watch?v=Fl3h9t087Pk

**Comment by thieu1995** [comment]
@hanamthang ,

You may find the feature selection with mealpy from here: https://github.com/thieu1995/mealpy-feature-selection
