### ISSUE TITLE
consult

### ISSUE THREAD

**Issue by tumu1234** [thieu1995/mealpy#51]
Hello author when I use your this mealpy prompt has‘’No module named 'mealpy.bio_based'; 'mealpy' is not a package”，What is the reason for this？

**Comment by thieu1995** [comment]
@tumu1234 ,
Have you installed mealpy yet?
Try to use this command in your terminal:

`pip install mealpy == 2.4.0`

Thanks

**Comment by tumu1234** [comment]
Hello, I have installed Mealpy, but the same error is reported.No module named 'mealpy.bio_based'; 'mealpy' is not a package



Thanks

**Comment by thieu1995** [comment]
Can you take a snapshot image of the error and post here? and what OS (windows, linux) and package management (pip, conda, miniconda) are you using?

**Comment by tumu1234** [comment]
我使用的是windows，用的pip安装，上传图片是怎么上传呢

**Comment by tumu1234** [comment]
[Doc5.docx](https://github.com/thieu1995/mealpy/files/8330590/Doc5.docx)

**Comment by tumu1234** [comment]
Are you unable to install with PIP now?


Thanks

**Comment by thieu1995** [comment]
![howtouploadimage](https://user-images.githubusercontent.com/12763861/159647765-e96ab5ee-6c39-425b-baa9-08a8973b8b71.png)
See the figure you will know how to upload image.

Are you new to python? Why did you name your file same as "mealpy" package?
You can name your script file as anything else, just not other package or python keyword. For example, hello.py, my_first_script.py,....
Please change your script name and try again.
Mealpy can install in most OS system (win, linux), and PM such as pip or conda.

**Comment by tumu1234** [comment]
Thank you very much. I'm really new to Python and I'm not very good at it.
