### ISSUE TITLE
GCO algorithm may has some mistakes.

### ISSUE THREAD

**Issue by Doradx** [thieu1995/mealpy#55]
Dear thieu1995,
I have been studying this module for a while, it's a nice job!
But I may have found some mistakes during using the GCO algorithm.

According to the [original paper](http://dx.doi.org/10.2991/ijcis.2018.25905179), the GCO algorithm will update the life-signal during the light-zone process, just as shown below.
![image](https://user-images.githubusercontent.com/23170065/160756642-a15fd46b-c58d-4417-8ebf-c0a1e615e0d0.png)
But in the source code, I found that the cell counter (dyn_list_cell_counter) is updated instead of life-signal (dyn_list_life_signal).
https://github.com/thieu1995/mealpy/blob/e3e5cfcb3dbdbba9fec007e3b2e745abb5f93b06/mealpy/system_based/GCO.py#L96-L102
And the life-signal seems non-changed during the whole evolution.

Is it a mistake?

**Comment by Doradx** [comment]
In the mutation process, the B-cell with more counter has more probability to crossover with other B-cells according to the description in the paper.
![description about the mutation process](https://user-images.githubusercontent.com/23170065/160762013-7d4127e4-bea1-49c0-b50c-3c185e9e7a69.png)

![mutation algorithm](https://user-images.githubusercontent.com/23170065/160761980-909d67fe-56dc-4b22-955e-7cdee6591378.png)

In the source code, I found that each population is been considered equal in both BaseGCO and  OriginGCO, which is different from the original paper.
https://github.com/thieu1995/mealpy/blob/e3e5cfcb3dbdbba9fec007e3b2e745abb5f93b06/mealpy/system_based/GCO.py#L85-L89
https://github.com/thieu1995/mealpy/blob/e3e5cfcb3dbdbba9fec007e3b2e745abb5f93b06/mealpy/system_based/GCO.py#L174-L177

All of the above differences show that the BaseGCO and  OriginGCO have key differences from the original paper, which may affect the results. 

I think significant notes should be marked in the README to let anyone who wants to use this algorithm know.

**Comment by thieu1995** [comment]
@Doradx ,

Thanks for fixing this, I will merge your pull request and may re-read your fixing code. I haven't looked at it closely enough.
