### ISSUE TITLE
how add our dataset?

### ISSUE THREAD

**Issue by seyyedjavadrazavi** [thieu1995/mealpy#63]
Hi there. 
I am new to this area and I want to use the SFO algorithm on my dataset. And I wonder how I can pass my dataset to the code as the input?
Is there anywhere that algorithm gets data as input? or does it works with its data?

thanks, in advance.

**Comment by thieu1995** [comment]
Hi @seyyedjavadrazavi ,

There is no way you can add dataset as input to this kind of metaheuristic algorithm. You should learn some basic about what is optimization problem, what is meta-heuristic algorithm. You should start with Particle Swarm Optimization from this video.
https://www.youtube.com/watch?v=JhgDMAm-imI

**Comment by seyyedjavadrazavi** [comment]
I think so. 
Thanks.
