### ISSUE TITLE
BUG in SSpiderO

### ISSUE THREAD

**Issue by ezraile** [thieu1995/mealpy#66]
Run SSpiderO algorithm with more than 80 epochs was issued by this error:

python3.7/dist-packages/mealpy/swarm_based/SSpiderO.py in _survive(self, pop, pop_child)
    255         pop_child = self.get_sorted_strim_population(pop_child, n_child)
    256         for i in range(0, n_child):
    257             if self.compare_agent(pop_child[i], pop[i]):
    258                 pop[i] = deepcopy(pop_child[i])
    259         return pop

IndexError: list index out of range

**Comment by thieu1995** [comment]
Hi @ezraile ,
Which version of mealpy are you using? I tested with 1000 epochs and it is working fine.

**Comment by ezraile** [comment]
I have updated my library to 2.4.2 version, but I come to same result.

1 from mealpy.swarm_based import SSpiderO
      2 optimizer = SSpiderO.BaseSSpiderO(problem, epoch=200, pop_size=100)
----> 3 optimizer.solve()


[/usr/local/lib/python3.7/dist-packages/mealpy/swarm_based/SSpiderO.py](https://localhost:8080/#) in survive__(self, pop, pop_child)
    261         pop_child = self.get_sorted_strim_population(pop_child, n_child)
    262         for i in range(0, n_child):
--> 263             if self.compare_agent(pop_child[i], pop[i]):
    264                 pop[i] = deepcopy(pop_child[i])
    265         return pop

**Comment by thieu1995** [comment]
@ezraile ,
It is hard to know where the problem comes from, especially when it works fine for me. 
Can you share the screenshot of the problem you are trying to solve and the full shown error? 
Or better create a google colab test and send me an invitation. I can check it for you.
