### ISSUE TITLE
Hybrid GWO and WOA

### ISSUE THREAD

**Issue by Akwasi-Richie** [thieu1995/mealpy#67]
Can you please add a hybrid GWO and WOA as proposed by Obadiah _et al_  2021??

Link to paper https://sci-hub.se/https://doi.org/10.1177/10775463211003402

Thank you

**Comment by thieu1995** [comment]
@Akwasi-Richie ,

You can find it here: https://github.com/thieu1995/mealpy/blob/dev/2.5.1/mealpy/swarm_based/GWO.py#L179

I will close this issue now.
