### ISSUE TITLE
Passing other variables 

### ISSUE THREAD

**Issue by appreciator** [thieu1995/mealpy#69]
Hi, Thieu,

Mealpy is a very powerful code. Many thanks for your great work.

When I am using GA of Mealpy in a "process" parallel training mode, I hope to pass some parameters, e.g., named "paras", into the fitness calculation function. These parameters are timely consumming for calculation and would not change during the optimization, therefore I hope to calculate them in the main function before calling Mealpy. 

However, when in a multi-processing mode, if I define "global paras" in the fitness subfunction, there would an error: "NameError: name 'paras' is not defined".

Would you mind telling me how to deal with this problem? I would really appreciate your help.

Best regards
Zuyu Li

**Comment by appreciator** [comment]
Hi, Thieu,

The following is a very simple code just for description of my problem. In fact, what I hope to pass as "paras" is an array obtained by timely consumming calculation. 

from mealpy.evolutionary_based import GA
import numpy as np

def fitness_func(solution):
    global paras 
    objVal = np.sum(solution**paras)

    return objVal

if __name__ == '__main__':
    
    paras = 2
        
    problem_dict = {
        "fit_func": fitness_func,
        "lb": [-100, -20, -3, -0.1],
        "ub": [2.5, 3.6, 4.7, 5.8],
        "minmax": "min",
        "log_to": "file",
        "log_file": "result.log"
    }
    
    ga_model = GA.BaseGA(problem_dict, epoch=1, pop_size=10)
    best_position, best_fitness_value = ga_model.solve(mode="process")
    
    print(best_position)
    print(best_fitness_value)

**Comment by appreciator** [comment]
I am using Mealpy 2.4.1 in Windows 64bit with Python 3.7

**Comment by appreciator** [comment]
If I change the code to the following, although "paras" can be used in fitness subfunction now, the timely consumming calculation of "paras" would be repeated for many times.

from mealpy.evolutionary_based import GA
import numpy as np
paras = 2 # paras = func() would be repeated called when using Mealpy in "process" mode
print(paras)

def fitness_func(solution):
    global paras 
    objVal = np.sum(solution**paras)

    return objVal

if __name__ == '__main__':
        
    problem_dict = {
        "fit_func": fitness_func,
        "lb": [-100, -20, -3, -0.1],
        "ub": [2.5, 3.6, 4.7, 5.8],
        "minmax": "min",
        "log_to": "file",
        "log_file": "result.log"
    }
    
    ga_model = GA.BaseGA(problem_dict, epoch=1, pop_size=10)
    best_position, best_fitness_value = ga_model.solve(mode="process")
    
    print(best_position)
    print(best_fitness_value)

**Comment by thieu1995** [comment]
Hi @appreciator ,

Thanks for the question. I fixed this problem yesterday in the new version 2.4.2.
Please read the document for this matter. 
https://mealpy.readthedocs.io/en/latest/pages/general/guide_to_use_model.html#more-on-fitness-function

**Comment by appreciator** [comment]
Hi, Thieu,

Thank you very much for your quick reply. I have tried the newest version 2.4.2, and it works fine if I pass some arrays as "data" for the fitness function. However, since I am using Python to call Matlab function, I have to pass some MatlabEngine objects (a kind of special objects ,different from arrays, lists, dicts) as "data" for the fitness function. When I tried to do so, there is an error: Unrecognized function or variable '__getstate__'
It sees that there is somewhere in Mealpy code trying to call the method '__getstate__' to "data"? Would you mind telling me where to remove such lines of codes? I think MatlabEngine object does not support '__getstate__' and therefore errors happen.

I would really appreciate your patient help.

Best regards,
Zuyu Li

**Comment by appreciator** [comment]
In addition, this error "Unrecognized function or variable 'getstate'", only happens in "process" mode. When using "thread" and "single" mode, passing and calling MatlabEngine objects in fitness function can obtain correct result and no errors.

**Comment by thieu1995** [comment]
@appreciator ,

I don't think the error "getstate" related to mealpy or multiprocessing mode. I have searched but found nothing on google. It may come from Matlab engine. Anyway, if it can run on "thread" mode, I recommend you try to use this mode. It is also parallel mode but instead of using multiple cores. It uses multiple threads to do the task.

**Comment by appreciator** [comment]
Thank you, Thieu
