### ISSUE TITLE
Issue with BaseMFO

### ISSUE THREAD

**Issue by akshay710vs** [thieu1995/mealpy#71]
from meal.swarm_based.MFO import BaseMFO is not loading. 

Can you help me with feature selection on Leukemia binary dataset with the MFO.

Dataset => https://www.kaggle.com/datasets/crawford/gene-expression?resource=download

**Comment by thieu1995** [comment]
Hi @akshay710vs ,
You can follow the examples from here to do feature selection.
https://github.com/thieu1995/MHA-FS
