### ISSUE TITLE
May I contribute a parallel version of IQSA implementation for this project?

### ISSUE THREAD

**Issue by daylightsaving** [thieu1995/mealpy#75]
Hello, @thieu1995:

Firstly, this project is so helpful for researchers & engineers who work on complicated problems. 
When I simply applied one of them(Improved QSA) on my optimization problem(tuning cascaded filters' params), the appropriate hyper-params([epoch, pop_size]) could really acquire excellent results!
However, the original version of implementation consumed too much time on each epoch when the pop_size was relatively large(On my problem, with [epoch=200, pop_size=400], it cost about 750ms on each epoch and 160,208ms in total.).
After some deeper analysis upon the code time-consuming, the major cost came from two parts(One is serial calculation of the cascaded filter response, another is the serial process of IQSA's default algorithm). 
Then I did some code reconstruction on above two sections according to the principle of vectorization and parallelization and got 18x ~ 104x acceleration compared with original version on various [epoch, pop_size] sets(The same [200, 400] hyper-parameter set by the boosted version only cost 45ms on each epoch and 8900ms in total, which was about 18x).
And could you spend some time to review my parallel version of code to judge whether it contains any mistakes.

Best Regards,
Liu.alex

**Comment by thieu1995** [comment]
Hi @daylightsaving ,

+) First, vectorization on computation equations of meta-heuristic algorithms (MHA) is not significantly fast than using for, while loop. If the cost to calculate your objective is around > 1 minute. It will not matter using vectorization or for, while loop. You can try to just vectorization on your objective function and keep the IQSA as the original one in my library. And compare the results between two tests, which one is faster? And how much time can it reduce?

+) Your short or slow test depends mainly on the cost of calculating the objective function and algorithm. 
	+ For example, each time you calculate your objective function, it costs 1 minute. However, suppose you run the whole epoch (whole loop of an algorithm) without computing the objective function. In that case, it will only cost around a second. So vectorization on the equation doesn't mean much here because the time you need depends mainly on calculating the objective function. 
	+ Besides, IQSA contains 4 serial phases, meaning in each epoch, it will update the population 4 times (The other algorithm is only updated 1 or 2 times), so if you reduce the pop_size from 400 to 100. Each epoch will run faster (400/100)*4*c (c: is the time to calculate your objective function). 

+) It would be best if you tried to set epoch=500 and pop_size=100. I think it will show better results than epoch=200 and pop_size=400 and also run faster. 

+) The IQSA already has a parallel version. You can try this:

	```
model = OriginalQSA(problem_dict1, epoch, pop_size)
	model.solve(mode="thread", n_workers=5)			# Using 5 threads to solve your problem 
	# or 
	model.solve(mode="process", n_workers=2)		# Using 2 process to solve your problem
```
	
+) If you have your own parallel version of IQSA, you can show it here. I will check it for you. 

+) I suggest you make a pull request with your parallel IQSA and an example for it. The example, you can code in the application folder, just like a guy who made a path planning example. 
https://github.com/thieu1995/mealpy/tree/master/examples/applications

Best regards,
Thieu

**Comment by daylightsaving** [comment]
@thieu1995 
Thank you for your detailed reply and further comment. I will double-check the work flow of the new version and do some time consuming experiment more completely. Then a PR will be created as your suggestion.
