### ISSUE TITLE
[BUG]: Several tests are failing during collection

### ISSUE THREAD

**Issue by firefly-cpp** [thieu1995/mealpy#76]
### Description of the bug

==================================== ERRORS ====================================
_________________ ERROR collecting tests/bio_based/test_BBO.py _________________
In test_epoch_BBO: function uses no argument 'problem'
_________________ ERROR collecting tests/bio_based/test_EOA.py _________________
In test_epoch_EOA: function uses no argument 'problem'
_________________ ERROR collecting tests/bio_based/test_IWO.py _________________
In test_epoch_IWO: function uses no argument 'problem'
_________________ ERROR collecting tests/bio_based/test_SBO.py _________________
In test_epoch_SBO: function uses no argument 'problem'
_________________ ERROR collecting tests/bio_based/test_SMA.py _________________
In test_epoch_SMA: function uses no argument 'problem'
_________________ ERROR collecting tests/bio_based/test_VCS.py _________________
In test_epoch_VCS: function uses no argument 'problem'
_________________ ERROR collecting tests/bio_based/test_WHO.py _________________
In test_epoch_WHO: function uses no argument 'problem'

### Steps To Reproduce

python -m pytest

**Comment by thieu1995** [comment]
fixed!
