### ISSUE TITLE
[BUG]: Optimization direction is wrong when `max` is set for `minmax` setting

### ISSUE THREAD

**Issue by lewis738** [thieu1995/mealpy#77]
### Description of the bug

I'm using ACOR optimizer, and i set "minmax" as  "max",
when i just started to solve, the optimizer selected the max fitness as the global best,
But the bug is, as the epoches goes on, the current fitness is decresing!
A optional solution is: add a minus sign to the object function, and set `minmax` as `min`
在选用ACOR算法，"minmax"设置为 "min"时候，优化方向的方向错误
即：在初代种群中选出了fitness最大的一组后，后续迭代似乎在尝试最小化fitness，输出的信息如后续Info所示，
可考虑的解决方案：给目标函数加上负号，将`minmax`修改为`min`

### Steps To Reproduce

1. use ACOR optimizer( other optimizers not tested)
2. set `minmax` as `min`
3. start solving

### Additional Information

Epoch: 1, Current best: -7.61656849045883, Global best: 37.61266673850652, 
Epoch: 2, Current best: -8.29316400787176, Global best: 37.61266673850652, ......
Epoch: 15, Current best: -24.07365247725762, Global best: 37.61266673850652, ......
Epoch: 100, Current best: -27.76862755410546, Global best: 37.61266673850652,

**Comment by thieu1995** [comment]
Hi @lewis738 ,
It is not a bug. You should understand the current best and global best

The current best is the best fitness value in the current epoch/iteration/generation.

The global best is the best fitness value found so far (after several epochs/iterations/generations).

So the global best fitness will decrease or increase each epoch (min/max problem). But the current best really depends on each algorithm.

If the design of that algorithm is good, then the current fitness will increase each epoch (max-problem). Else the current fitness will go up and down in each epoch.

**Comment by lewis738** [comment]
Thanks @thieu1995 ,
I think I have fully understood the difference between current best and global best.

The problem is when I tested the same problem, and 
1. set `minmax` as `max`, the current best decreased continually, and the global hadn't updated since initialized. As provided above and below, in dditional Information.
2. set `minmax` as `min`, and added a minus sign to the object function, all went well. the current best decreased generally, and sometimes updated the global best. As provided below.

That't the reason why I think some settings which should be changed but had been ignored, when setting `minmax`. And that is why I considered the problem as a bug.

# Additional Infomation
## `minmax` = `min`
Epoch: 1, Current best: -27.64056667139165, Global best: -27.64056667139165
Epoch: 2, Current best: -35.86774261288706, Global best: -35.86774261288706
Epoch: 5, Current best: -39.54206272260019, Global best: -39.54206272260019
Epoch: 100, Current best: -40.40415236547533, Global best: -40.40415236547533

## `minmax` = `max`
Epoch: 1, Current best: -7.61656849045883, Global best: 37.61266673850652,
Epoch: 2, Current best: -8.29316400787176, Global best: 37.61266673850652, ......
Epoch: 15, Current best: -24.07365247725762, Global best: 37.61266673850652, ......
Epoch: 100, Current best: -27.76862755410546, Global best: 37.61266673850652,

**Comment by thieu1995** [comment]
@lewis738 ,

The "minmax" setting is used only in comparison between agents. 
And the global best is found by comparing the start-global best (the initialized population) with the current best in that epoch. 

The global best is not changing from the start. Maybe that is the final global best. Or the algorithm is so weak that it can not update it anymore. 
You can clearly see this in your example, in the "max" case. The current best is not better than the start-global best. Therefore it is not updated. The start-global best is still the best one. 

Changing the max and min problem by adding the minus sign or division operator will change the shape of the fitness function. And optimization algorithm action will also be changed by that. 

I think you can try other optimizers to see if it is really the final global best or not. For example, try TLO, WOA, SHADE, L-SHADE, AEO, MRFO, and QSO,...
