### ISSUE TITLE
[FEAT]: multi-threading for the algorithms

### ISSUE THREAD

**Issue by Lym1028987502** [thieu1995/mealpy#79]
### Description

thank you for updating the mealpy2.5, which is more useful. I used to come up with the problem for the mulit-threading about PSO, which has been fixed up. but i found that many other algorithoms can not reach the number of threading as i set the workers. for example, when i use  print(threading.active_count()) in fitness function, and the workers set as 16, some algorithms print 1, 3,or 4, which were not 15/16 as expected. And the GA ,PSO didn't have such problems yet. i hope you can help me to solve the problem,  looking forward to you replying, thank you !

**Comment by thieu1995** [comment]
Hi @Lym1028987502 ,

There are several algorithms that can't be implemented in the parallel mode that do not destroy the original algorithms. Those algorithms are not only complex but also long and hard to read. 
Currently, when you set up the parallel mode and workers in those algorithms, it will not show any error, but underneath, they're actually still running sequential mode.

I will add the warning for those algorithms that they do not support parallel mode.
