### ISSUE TITLE
[BUG]: Roulette wheel selection is broken

### ISSUE THREAD

**Issue by scilari** [thieu1995/mealpy#80]
### Description of the bug

Roulette wheel selection is supposed to return parent indices proportional to their fitness. However, the fitness "scaling" done in Optimizer.get_index_roulette_wheel_selection (L522) breaks this property.

For example, fitness [1, 1, 1.01] is supposed to return each index with about 33% probability. However, the current implementation returns the 3rd element always, as the first two elements are scaled to zero.

This poses problems also in non-toy cases, where the population will easily collapse to one individual if the rest of the population has very self-similar but lower fitness. This will destroy the population diversity.

Also the final selection could benefit from simply using cumulative sum and searchsorted for clarity.

### Steps To Reproduce

Do selection with [1, 1, 1.01] or similar fitness.

**Comment by thieu1995** [comment]
@scilari ,

You can find my solution here: https://github.com/thieu1995/mealpy/blob/dev/2.5.1/mealpy/optimizer.py#L520

**Comment by scilari** [comment]
@thieu1995 : I have to disagree that it does not happen in real cases. The current implementation will fail in any situation where the fitness landscape is fairly or mostly flat and contains several local optima. In this kind of situation, when one of the individuals finds a local optimum, it immediately gets _all_ of the weight due to the faulty scaling operation* and the population collapses to that individual, as it will be 100% of the selected parents.

Many of the problems where for example GAs usually excel, are exactly like this: multimodal problems with complex fitness landscape where it is crucial to maintain the population diversity. Have you ran some benchmarks to show that the current implementation only rarely fails when compared to standard roulette wheel selection?

The three element fitness array was just an illustrating example. If needed, I can probably implement a fitness landscape where the current implementation will fail almost 100% of time, regardless of population size, whereas a correct roulette wheel selection will succeed.

My suggestion: Implement correct roulette wheel selection for positive weights as defined in the literature (prob. is proportional to fitness). Then implement some explicit helper functions to map negative weigths to positive ones. I think trying to handle too many cases under the hood can lead to problems similar to the "scaling" here.

Your suggestion: Isn't that what the roulette wheel selection should be doing by default?

* Funnily enough, one of common ways to prevent this kind of premature convergence and to add robustness to outliers is to add a uniform tail (a positive constant) to the fitness (or likelihood) functions. This is the exact opposite of what the scaling is doing here.

**Comment by scilari** [comment]
I will have to read your suggested solution with more time, but looking at the comment it seems that my example made you think this is just some kind of edge case, where values are exactly the same. It is not, and the same issue will happen also with different values, e.g. with a fitness landscape with very low gradients and some local optima. The issue is still present with

fit = np.random.rand(100) * 0.0001 + 1  # flat landscape
fit[-1] = 1.1  # local optima as a small 10% bump

Here too, even though the values are different, they are basically a uniform distribution. However, due to scaling, majority of the weight (94%) will go to the last element, while it should be around 1.1%.

**Comment by scilari** [comment]
> Still, in case we get the situation you mentioned. I would propose randomly selecting with a probability corresponding to each solution's fitness (using the choice function in NumPy: https://numpy.org/doc/stable/reference/random/generated/numpy.random.choice.html)

Hmmm... why are you taking the exponential from the scaled fitnesses? These probabilities do not correspond to the fitness of ethe solutions, and the result does not correspond to roulette wheel selection either. I'm a bit puzzled here: what wrong with simply normalizing the unscaled fitnesses norm_fs = fs / np.sum(fs),  and then using np.choice(range(norm_fs), p=norm_fs)?

This can be made to handle _all_ negative fitnesses more properly as well by:

**Comment by thieu1995** [comment]
> Hmmm... why are you taking the exponential from the scaled fitnesses? These probabilities do not correspond to the fitness of the solutions, and the result does not correspond to roulette wheel selection either. I'm a bit puzzled here: what's wrong with simply normalizing the unscaled fitnesses norm_fs = fs / np.sum(fs), and then using np.choice(range(norm_fs), p=norm_fs)?
> 
> https://en.wikipedia.org/wiki/Fitness_proportionate_selection

I'm not sure why I took the exponential really. But the simple normalizing one is okay, no problem with that. I will fix to the simple one.

**Comment by thieu1995** [comment]
> I will have to read your suggested solution with more time, but looking at the comment it seems that my example made you think this is just some kind of edge case, where values are exactly the same. It is not, and the same issue will happen also with different values, e.g. with a fitness landscape with very low gradients and some local optima. The issue is still present with
> 
> fit = np.random.rand(100) * 0.0001 + 1 # flat landscape fit[-1] = 1.1 # local optima as a small 10% bump
> 
> Here too, even though the values are different, they are basically a uniform distribution. However, due to scaling, majority of the weight (94%) will go to the last element, while it should be around 1.1%.

@scilari 
Thanks for the detailed explanation. I tested, and the results were like you said. It will always return the local optimal. I will remove the scaling part. Then now, I need to handle negative values. Do you have any suggestions for this matter?

**Comment by scilari** [comment]
@thieu1995 Thanks for testing the issue and verifying it.

One simple way for negative and other non-roulettable weights would be to require the user to come up with a mapping to non-negative values, as they probably knows the interpretation of their fitness values the best.

One approach I've seen to reverse fitnesses is to use reciprocals. This could also be used to create weights from all-negative values xs by [1/abs(x) for x in xs]. This preserves some of the desirable/intuitive properties, such as -10 being ten times less likely to be chosen than -1 (analogous to 1 and 10 on positive side), but does not work for zero values, for example. This could be offered as a well-documented helper method, to be more explicit about the mapping to be used.

As I don't think there's a universal way to map arbitrary values to "probabilities", I don't think it would be unreasonable for the user to come up with a way that fits their purpose.

Note also how much easier this all is for tournament selection, luckily being the default! 😉
