### ISSUE TITLE
[FEAT]: Ask and Tell API interface

### ISSUE THREAD

**Issue by TamerAbdelmigid** [thieu1995/mealpy#82]
### Description

Can you please provide ask and tell interface, where I can get the entire population as input and evaluate it at once.
For Example the function to be evaluated is a ML model, which I can evaluate the entire population as a single batch and accelerate any algorithm.

**Comment by thieu1995** [comment]
@TamerAbdelmigid ,
Sorry, will have no option for that. You can read parallel training option instead. Not every algorithms are the same, and can be parallelization 

https://mealpy.readthedocs.io/en/latest/pages/general/simple_guide.html?highlight=parallel#training

**Comment by TamerAbdelmigid** [comment]
Thanks for your fast response.
