### ISSUE TITLE
[BUG]: EliteSingleGA() failed to get result

### ISSUE THREAD

**Issue by Qiuyi-Hong** [thieu1995/mealpy#84]
### Description of the bug

Hello @thieu1995 , 

Thanks for helping me by adding the elitism feature to this library. However, after I download the newest version, the algorithm failed to get the result and returned the traceback like: 

======================================
ValueError                                Traceback (most recent call last)
 gaModel = GA.EliteSingleGA(epoch=100, pop_size=50, pc=0.9, pm=0.1, mutation="scramble", strategy=1, elite_best=1, elite_worst=1)
best_position_ga, best_fitness_value_ga = gaModel.solve(problem_pso)

File /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mealpy/optimizer.py:281, in Optimizer.solve(self, problem, mode, starting_positions, n_workers, termination)
    278 time_epoch = time.perf_counter()
    280 ## Evolve method will be called in child class
--> 281 self.evolve(epoch)
    283 # Update global best position, the population is sorted or not depended on algorithm's strategy
    284 pop_temp, self.g_best = self.update_global_best_solution(self.pop)

File /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mealpy/evolutionary_based/GA.py:558, in EliteSingleGA.evolve(self, epoch)
    555 pop_mom = cp.deepcopy(self.pop[self.n_elite_best+self.n_elite_worst:])
    556 for idx in range(self.n_elite_best, self.pop_size):
    557     ### Selection
--> 558     child1, child2 = self.selection_process_01__(pop_dad, pop_mom)
    559     ### Crossover
    560     if np.random.uniform() < self.pc:

File /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mealpy/evolutionary_based/GA.py:176, in BaseGA.selection_process_01__(self, pop_dad, pop_mom)
    174     list_fit_mom = np.array([agent[self.ID_TAR][self.ID_FIT] for agent in pop_mom])
    175     id_c1 = self.get_index_roulette_wheel_selection(list_fit_dad)
...
--> 544 return np.random.choice(range(0, size), p=prob)

File mtrand.pyx:937, in numpy.random.mtrand.RandomState.choice()

ValueError: probabilities are not non-negative

=======================================

The SingleGA() and even EliteMultiGA() run without an issue. So I suppose that there is something wrong with the EliteSingleGA(). 

Please let me know if there is anything to solve the problem. 

Thanks!

### Steps To Reproduce

1. Run: model = EliteSingleGA(epoch=100, pop_size=50, pc=0.9, pm=0.1, mutation="scramble", strategy=1, elite_best=1, elite_worst=1)
2. Run: best_position_ga, best_fitness_value_ga = model.solve(problem)
3. get the ValueError: probabilities are not non-negative

**Comment by thieu1995** [comment]
@Qiuyi-Hong ,

The parameters elite_best and elite_worst, you are not set it right. 
It should be the percent of elite best, and percent of elite worst. For example: elite_best = 0.1 (10% of population), elite_worst = 0.3 (30% of population). 
You can read the docs how to set parameters from here: 
https://mealpy.readthedocs.io/en/latest/pages/models/mealpy.evolutionary_based.html#module-mealpy.evolutionary_based.GA
