### ISSUE TITLE
Fitness Function Error

### ISSUE THREAD

**Issue by Akwasi-Richie** [thieu1995/mealpy#88]
I am trying to use the hybrid GWO_WOA algorithm but I keep running into an error provided in the second image. Kindly help me out. It was running yesterday but I had error which was in the line of, " Running two objective functions, specify obj_weights with Length:2". This was after the first epoch had finished running.

however, the error is not popping up but instead the fitness function error.

Code snippet
![Code](https://user-images.githubusercontent.com/70091983/203567694-fa2acad4-76e1-405e-b0e8-46196b70004e.png)

Error Snippet
![Error_Msg](https://user-images.githubusercontent.com/70091983/203567724-bd22b8df-5d9e-41f0-8ce2-e79bb72d680d.png)

**Comment by thieu1995** [comment]
@Akwasi-Richie ,

In the first picture. It shows that you are using the latest version 2.5.1.
So make sure mealpy in your laptop is latest by 

pip install mealpy == 2.5.1

or 

pip install mealpy --upgrade

In the first picture, the problem dictionary is wrong at: obj_weight, It should be: obj_weights
Besides, the termination=termination_dict is wrong at that place. It should be in model.solve(termination=termination_dict)
Check the document: https://mealpy.readthedocs.io/en/latest/pages/general/advance_guide.html#stopping-condition-termination

**Comment by Akwasi-Richie** [comment]
Thanks, will do that
