### ISSUE TITLE
Modified Spotted Hyena optimization

### ISSUE THREAD

**Issue by alirezaghader** [thieu1995/mealpy#9]
@thieu1995 hi!
May you say what modifications you applied to the Spotted Hyena optimization?

**Comment by thieu1995** [comment]
Lots of algorithms I implemented long time ago. So I didn't remember it what I modified exactly. If you have any other questions, leave it here. I will comeback and read the paper again and answer you later.

**Comment by alirezaghader** [comment]
@thieu1995 Thank you. I wait for ur reply. If I face any other error I will leave them here (hoping not to face).
you have done a great job

**Comment by thieu1995** [comment]
Hi @alirezaghader ,

I have checked the algorithm that I wrote a long time ago. I didn't change anything, so basically it is original version of SHO.
