### ISSUE TITLE
[FEAT]: Add QLESCA optimizer

### ISSUE THREAD

**Issue by suanzy** [thieu1995/mealpy#91]
### Description

Hi MealPy Dev team,

I will like to use this optimizer but the author has it in Matlab. Is it possible to include in MealPy? Attached is the original PDF.  Thanks.
[1-s2.0-S0957417421017048-main.pdf](https://github.com/thieu1995/mealpy/files/10175331/1-s2.0-S0957417421017048-main.pdf)

**Comment by thieu1995** [comment]
Hi @suanzy ,

This is an interesting algorithm. I will try to add it in the next version.

**Comment by thieu1995** [comment]
@suanzy ,

It will be in the next version.
