### ISSUE TITLE
RuntimeWarning: invalid value encountered in divide   prob = final_fitness / np.sum(final_fitness)

### ISSUE THREAD

**Issue by abcdhope** [thieu1995/mealpy#92]
There are some models that will show NAN values when testing functions, and the location of the error is: `RuntimeWarning: invalid value encountered in divide  prob = final_fitness / np.sum(final_fitness)`

**Comment by thieu1995** [comment]
@abcdhope,

This error is typical the error of the fitness function that designed by user. You need to check the fitness function for some special cases. 
You can give me more information about your problem, your fitness function. So I can help you to solve it.
