### ISSUE TITLE
[BUG]: get_index_roulette_wheel_selection 

### ISSUE THREAD

**Issue by abdennourAzerine** [thieu1995/mealpy#93]
### Description of the bug

the _get_index_roulette_wheel_selection_ method in the **optimizer.py** throw an error when all the values of the _list_fitness_ are equals. The final_fitness will be a vector of zeros and then you are deviding by the sum of this vector. Hence, we get "_ValueError : propabilities contain NaN_".

### Steps To Reproduce

.

**Comment by thieu1995** [comment]
This problem has been fixed in next version.
