### ISSUE TITLE
Artificial Bee Colony Algorithm

### ISSUE THREAD

**Issue by resooul** [thieu1995/mealpy#95]
### Description of the bug

The swarm-based Artificial Bee Colony Algorithm (ABC) is listed in the code. However, the codes belong to the Bees Algorithm (BA) in the literature. The name and references of the algorithm are located in the book Clever Algorithms explicitly. Accordingly, there is no ABC algorithm code in this repository. Please check this issue. 

### Steps To Reproduce

[swarm_based](https://github.com/thieu1995/mealpy/tree/master/mealpy/swarm_based)/ABC.py

**Comment by thieu1995** [comment]
Hi @resooul ,

Thanks for pointing it out. WIll be fixed in new version.
