### ISSUE TITLE
[FEAT]: Add Donkey and Smuggler Optimization Algorithm (DSO)

### ISSUE THREAD

**Issue by milhamm** [thieu1995/mealpy#96]
### Description

Hi MealPy Dev, 

Is it possible for you to implement Donkey and Smuggler Optimization Algorithm (DSO).
https://arxiv.org/abs/1904.09352

Thanks

**Comment by thieu1995** [comment]
@milhamm ,

I can't find the matlab code for benchmark function. There is only matlab code for TSP problem. Do you have this matlab code for benchmark function? I can convert matlab code to python code and add this algorithm to Mealpy.

**Comment by furqonfahlevi** [comment]
Hi @thieu1995 ,

I don't think the authors of Donkey and Smuggler Optimization Algorithm (DSO) (https://arxiv.org/abs/1904.09352) provide any other code than TSP problem.

**Comment by thieu1995** [comment]
@milhamm @milhamm 
Then It is hard for me to implement it. I looked at the paper, It is not similar to other nature-inspired papers. The equations are unclear, or I would say there are only a few equations in the paper. 
I think you guys can email and ask the authors to provide the Matlab code for benchmark functions. If they do not provide it, you know what it is. We should avoid this kind of algorithm and paper.

**Comment by thieu1995** [comment]
@milhamm , @milhamm 
Sorry, I have looked at the paper and I don't think I can implement this algorithm. This looks like a fake paper with fake results. Especially when considering there is no code for the benchmark function. Even the results of benchmark functions, some values in the table are noted with N/A. I am curious to know how this paper got accepted in this journal. However, from my point of view, we should avoid this kind of algorithms.
