### ISSUE TITLE
[BUG]: Verbose mode not working

### ISSUE THREAD

**Issue by twistfire** [thieu1995/mealpy#98]
### Description of the bug

Is it possible to mute the mealpy optimization output? 

Not to show the diagnostics messages all the time?

I have tried to use verbose argument in a problem definition - but it doesn't help. I got the full output on each iteration of optimization.
It is a bug or I am doing something wrong?

### Steps To Reproduce

Here is the toy code

```
import numpy as np
from mealpy.swarm_based.PSO import OriginalPSO

def fitness_function(x, addit_args: list, addit_args2: list):
    # x is a numpy array of shape (3,) containing the input variables
    # do some computation to evaluate the quality of the solution
    y = (x[0]-2)**2 + (x[1]-3)**2 + (x[2]-4)**2
    return y

def wrapped_fitness_function(x):
    list1 = [1]
    list2 = [2]
    res = fitness_function(x, addit_args=list1 , addit_args2=list2)

    return res

# create the array of initial positions for all particles 
pop_size = 1000
epoch = 5000

# if we will set criteria to stop the optimization
time_bound = 20 # sec

c1 = 2.05
c2 = 2.05

w_min = 0.4
w_max = 0.9

# defining the problem
problem_dict1 = {
    "fit_func": wrapped_fitness_function,
    "lb": [-5, -5, -5],
    "ub": [5, 5, 5],
    "minmax": "min",
    "verbose": False
}

# setting the termination criteria (!)
term_dict = {
    'mode': 'TB',
    'quantity' : time_bound 
    #"mode": "ES",
    #"quantity": 900
}


# define the bounds and initial conditions for the input variables
x0 = [1, 2, 3] # initial guess
print('x0 = ', x0)

# creating the start positions for a particles

start_positions = np.zeros((pop_size, 3))
start_positions[0, :] = x0  # set first row to x0

for i in range(1, pop_size):
    # initialize the remaining rows randomly within the bounds
    start_positions[i, :] = np.random.uniform(low=problem_dict1["lb"], high=problem_dict1["ub"], size=3)
    #start_positions[i, :] = x0

# create an instance of the optimizer
model_OPSO1 = OriginalPSO(epoch, pop_size, c1, c2, w_min, w_max)

best_position, best_fitness = model_OPSO1.solve(
    problem=problem_dict1,
    starting_positions=start_positions,
    termination=term_dict,
    #mode='process',
    n_workers=10
)

print('*'*80)
print('*'*80)
print(best_position)
print(best_fitness)
print('*'*80)
print('*'*80)
```

it gives the output every iteration..
---
2023/03/04 02:44:21 PM, INFO, mealpy.swarm_based.PSO.OriginalPSO: Solving single objective optimization problem.
2023/03/04 02:44:21 PM, WARNING, mealpy.swarm_based.PSO.OriginalPSO: Stopping condition mode: Time Bound, with maximum value is: 20
2023/03/04 02:44:21 PM, INFO, mealpy.swarm_based.PSO.OriginalPSO: >Problem: P, Epoch: 1, Current best: 0.2500288827086843, Global best: 0.2500288827086843, Runtime: 0.05010 seconds
2023/03/04 02:44:21 PM, INFO, mealpy.swarm_based.PSO.OriginalPSO: >Problem: P, Epoch: 2, Current best: 0.2500288827086843, Global best: 0.2500288827086843, Runtime: 0.04320 seconds
2023/03/04 02:44:21 PM, INFO, mealpy.swarm_based.PSO.OriginalPSO: >Problem: P, Epoch: 3, Current best: 0.2500288827086843, Global best: 0.2500288827086843, Runtime: 0.04247 seconds
2023/03/04 02:44:21 PM, INFO, mealpy.swarm_based.PSO.OriginalPSO: >Problem: P, Epoch: 4, Current best: 0.06405612655628029, Global best: 0.06405612655628029, Runtime: 0.04020 seconds
2023/03/04 02:44:21 PM, INFO, mealpy.swarm_based.PSO.OriginalPSO: >Problem: P, Epoch: 5, Current best: 0.06405612655628029, Global best: 0.06405612655628029, Runtime: 0.10096 seconds
2023/03/04 02:44:21 PM, INFO, mealpy.swarm_based.PSO.OriginalPSO: >Problem: P, Epoch: 6, Current best: 0.06405612655628029, Global best: 0.06405612655628029, Runtime: 0.03960 seconds
2023/03/04 02:44:21 PM, INFO, mealpy.swarm_based.PSO.OriginalPSO: >Problem: P, Epoch: 7, Current best: 0.06405612655628029, Global best: 0.06405612655628029, Runtime: 0.03929 seconds
2023/03/04 02:44:21 PM, INFO, mealpy.swarm_based.PSO.OriginalPSO: >Problem: P, Epoch: 8, Current best: 0.06405612655628029, Global best: 0.06405612655628029, Runtime: 0.03924 seconds
2023/03/04 02:44:21 PM, INFO, mealpy.swarm_based.PSO.OriginalPSO: >Problem: P, Epoch: 9, Current best: 0.06405612655628029, Global best: 0.06405612655628029, Runtime: 0.03872 seconds
2023/03/04 02:44:21 PM, INFO, mealpy.swarm_based.PSO.OriginalPSO: >Problem: P, Epoch: 10, Current best: 0.06405612655628029, Global best: 0.06405612655628029, Runtime: 0.03770 seconds
2023/03/04 02:44:21 PM, INFO, mealpy.swarm_based.PSO.OriginalPSO: >Problem: P, Epoch: 11, Current best: 0.06405612655628029, Global best: 0.06405612655628029, Runtime: 0.03941 seconds
2023/03/04 02:44:21 PM, INFO, mealpy.swarm_based.PSO.OriginalPSO: >Problem: P, Epoch: 12, Current best: 0.06405612655628029, Global best: 0.06405612655628029, Runtime: 0.04043 seconds
2023/03/04 02:44:21 PM, INFO, mealpy.swarm_based.PSO.OriginalPSO: >Problem: P, Epoch: 13, Current best: 0.06405612655628029, Global best: 0.06405612655628029, Runtime: 0.04298 seconds
2023/03/04 02:44:21 PM, INFO, mealpy.swarm_based.PSO.OriginalPSO: >Problem: P, Epoch: 14, Current best: 0.06405612655628029, Global best: 0.06405612655628029, Runtime: 0.03584 seconds
....
---

Is it possible to mute it or just give the results each 100 iterations r print if some changes occurring during the iteration (e.g. finded new value for global best solution)?

**Comment by thieu1995** [comment]
@twistfire ,

Please read the docs. It is not the bug.
https://mealpy.readthedocs.io/en/latest/pages/general/advance_guide.html#log-training-process

You don't want the log, you can set "log_to" = "None"
