### ISSUE TITLE
[FEAT]: ChOA.py is empty

### ISSUE THREAD

**Issue by MrJpudding** [thieu1995/mealpy#99]
### Description

When can the code for ChOA be updated?

**Comment by thieu1995** [comment]
@MrJpudding ,

There are a few versions on Matlab repository. I don't know which one is from original paper. 
Can you help me to identify that?

**Comment by MrJpudding** [comment]
@thieu1995 The link to original version(ChOA). [https://ww2.mathworks.cn/matlabcentral/fileexchange/76763-chimp-optimization-algorithm?s_tid=srchtitle](url)
In addition, this is an upgraded version of it (WChOA).  [https://ww2.mathworks.cn/matlabcentral/fileexchange/99344-a-weighted-chimp-optimization-algorithm?s_tid=FX_rc1_behav](url)
The authors of both are M. Khishe.

**Comment by thieu1995** [comment]
@MrJpudding,

Thank you, I will try to implement based on your suggestion.
